ArtistsMVCDemo/Models/Album.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace ArtistsMVCDemo.Models
{
    public class Album
    {
        public int ID { get; set; }

        [Required(ErrorMessage = "Title is required")]
        [StringLength(60, MinimumLength = 3)]
        public string Title { get; set; }

        [DataType(DataType.MultilineText)]
        public string Description { get; set; }

        public string Thumbnail { get; set; }

        [NotMapped]
        public HttpPostedFileBase ImageFile { get; set; }

        public ICollection<Song> Songs { get; set; }

        [ForeignKey("Artist")]
        public int ArtistId { get; set; }
        public Artist Artist { get; set; }
    }
}

ArtistsMVCDemo/Controllers/AlbumsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ArtistsMVCDemo.Models;
using ArtistsMVCDemo.Repositories;
using ArtistsMVCDemo.ViewModels;

namespace ArtistsMVCDemo.Controllers
{
    [Authorize]
    public class AlbumsController : Controller
    {
        //private ApplicationDbContext db = new ApplicationDbContext();
        private readonly IAlbumData _albumRepository;
        private readonly IArtistData _artistRepository;
        private readonly AlbumRepository _albumAdditionalMethods;

        public AlbumsController()
        {
            _albumRepository = new AlbumRepository();
            _artistRepository = new ArtistRepository();
            _albumAdditionalMethods = new AlbumRepository();
        }

        // GET: Albums
        public ActionResult Index()
        {
            var albums = _albumAdditionalMethods.GetAllWithArtist();
            return View(albums);
        }

        // GET: Albums/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Album album = _albumRepository.GetById(id);

            if (album == null)
            {
                return HttpNotFound();
            }

            return View(album);
        }

        // GET: Albums/Create
        public ActionResult Create()
        {
            //ViewBag.ArtistId = new SelectList(db.Artists, "ID", "FullName");
            var artists = _artistRepository.GetAll();
            var viewModel = new AlbumFormViewModel()
            {
                Album = new Album(),
                Artists = artists
            };
            return View(viewModel);
        }

        // POST: Albums/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Album album, HttpPostedFileBase ImageFile)
        {
            if (ModelState.IsValid)
            {
                if(ImageFile == null)
                {
                    album.Thumbnail = "na_image.jpg";
                }
                else
                {
                    album.Thumbnail = Path.GetFileName(ImageFile.FileName);
                    string fileName = Path.Combine(Server.MapPath("~/img/"), album.Thumbnail);
                    ImageFile.SaveAs(fileName);
                }
                _albumRepository.Create(album);
                return RedirectToAction("Index");
            }

            ViewBag.ArtistId = new SelectList(_artistRepository.GetAll(), "ID", "FullName", album.ArtistId);
            return View(album);
        }

        // GET: Albums/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Album album = _albumRepository.GetById(id);
            if (album == null)
            {
                return HttpNotFound();
            }
            ViewBag.ArtistId = new SelectList(_artistRepository.GetAll(), "ID", "FullName", album.ArtistId);
            return View(album);
        }

        // POST: Albums/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Album album)
        {
            if (ModelState.IsValid)
            {
                album.Thumbnail = Path.GetFileName(album.ImageFile.FileName);
                string fileName = Path.Combine(Server.MapPath("~/img/"), album.Thumbnail);
                album.ImageFile.SaveAs(fileName);

                _albumRepository.Update(album);
                return RedirectToAction("Index");
            }
            ViewBag.ArtistId = new SelectList(_artistRepository.GetAll(), "ID", "FullName", album.ArtistId);
            return View(album);
        }

        // GET: Albums/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Album album = _albumRepository.GetById(id);

            if (album == null)
            {
                return HttpNotFound();
            }

            return View(album);
        }

        // POST: Albums/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            _albumRepository.Delete(id);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _albumRepository.Dispose();
                _artistRepository.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ArtistsMVCDemo/Controllers/Api/AlbumsController.cs
using ArtistsMVCDemo.Dtos;
using ArtistsMVCDemo.Models;
using ArtistsMVCDemo.Repositories;
using AutoMapper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace ArtistsMVCDemo.Controllers.Api
{
    public class AlbumsController : ApiController
    {
        private readonly AlbumRepository _albumRepository;

        public AlbumsController()
        {
            _albumRepository = new AlbumRepository();
        }

        public IHttpActionResult GetAlbums()
        {
            return Ok(_albumRepository
                .GetAll()
                .Select(Mapper.Map<Album,AlbumDto>));
        }

        public IHttpActionResult GetAlbum(int id)
        {
            var album = _albumRepository.GetById(id);
            if (album == null)
                return NotFound();
            return Ok(Mapper.Map<Album,AlbumDto>(album));
        }

        [HttpPost]
        public IHttpActionResult CreateAlbum(AlbumDto albumDto)
        {
            if (!ModelState.IsValid)
                return BadRequest();

            var album = Mapper.Map<AlbumDto, Album>(albumDto);
            _albumRepository.Create(album);
            albumDto.ID = album.ID;
            return Created(new Uri(Request.RequestUri + "/" + album.ID), albumDto);
        }

        [HttpPut]
        public IHttpActionResult Update(int id, AlbumDto albumDto)
        {
            if (!ModelState.IsValid)
                return BadRequest();
            var albumInDb = _albumRepository.GetById(id);
            if (albumInDb == null)
                return NotFound();
                        
            Mapper.Map(albumDto, albumInDb);
            _albumRepository.Save();

            return StatusCode(HttpStatusCode.NoContent);
        }

        [HttpDelete]
        public IHttpActionResult DeleteAlbum(int id)
        {
            var albumInDb = _albumRepository.GetById(id);
            if (albumInDb == null)
                return NotFound();
            _albumRepository.Delete(id);
            return Ok(albumInDb);
        }

        [Route("myapi/Albums/GetTwo")]
        public IHttpActionResult GetFirstTwoAlbums()
        {
            return Ok(_albumRepository
                .GetFirstTwo()
                .Select(Mapper.Map<Album, AlbumDto>));
        }

        [Route("api/Albums/GetAllWithArtist")]
        public IHttpActionResult GetAllWithArtist()
        {
            return Ok(_albumRepository
                .GetAllWithArtist()
                .Select(Mapper.Map<Album, AlbumDto>));
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _albumRepository.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ArtistsMVCDemo/Views/Albums/Create.cshtml
@model ArtistsMVCDemo.ViewModels.AlbumFormViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Albums", FormMethod.Post, new { enctype = "multipart/form-data"}))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Album</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Album.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Album.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Album.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Album.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Album.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Album.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Album.ArtistId, "ArtistId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Album.ArtistId, new SelectList(Model.Artists, "ID","FullName"),"Select Artist", new { @class="form-control"})
                @Html.ValidationMessageFor(model => model.Album.ArtistId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Album.Thumbnail, htmlAttributes: new { @class="col-md-2"})
            <div class="col-md-10">
                <input type="file" name="ImageFile"/>
                @Html.ValidationMessageFor(model => model.Album.Thumbnail, "", new { @class="text-danger"})
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ArtistsMVCDemo/Views/Albums/Delete.cshtml
@model ArtistsMVCDemo.Models.Album

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Album</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Artist.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Artist.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ArtistsMVCDemo/Views/Albums/Details.cshtml
@model ArtistsMVCDemo.Models.Album

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Album</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Artist.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Artist.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ArtistsMVCDemo/Views/Albums/Edit.cshtml
@model ArtistsMVCDemo.Models.Album

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit","Albums", FormMethod.Post, new { enctype = "multipart/form-data"}))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Album</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.ID)

    <div class="form-group">
        @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ArtistId, "ArtistId", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("ArtistId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.ArtistId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Thumbnail, htmlAttributes: new { @class = "col-md-2" })
        <div class="col-md-10">
            <input type="file" name="ImageFile" />
            @Html.ValidationMessageFor(model => model.Thumbnail, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ArtistsMVCDemo/Views/Albums/Index.cshtml
@model IEnumerable<ArtistsMVCDemo.Models.Album>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Artist.FullName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Artist.FullName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>